/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThankYouImport } from './routes/thank-you'
import { Route as ServicesImport } from './routes/services'
import { Route as OfferImport } from './routes/offer'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutusImport } from './routes/aboutus'
import { Route as IndexImport } from './routes/index'
import { Route as OffersIndexImport } from './routes/offers/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthProfileImport } from './routes/auth/profile'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminProductsIndexImport } from './routes/admin/products/index'
import { Route as AdminProductOrdersIndexImport } from './routes/admin/productOrders/index'
import { Route as AdminOrdersIndexImport } from './routes/admin/orders/index'
import { Route as AdminOffersIndexImport } from './routes/admin/offers/index'
import { Route as AdminCarsIndexImport } from './routes/admin/cars/index'

// Create/Update Routes

const ThankYouRoute = ThankYouImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const OfferRoute = OfferImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutusRoute = AboutusImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OffersIndexRoute = OffersIndexImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRoute,
} as any)

const AdminProductsIndexRoute = AdminProductsIndexImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRoute,
} as any)

const AdminProductOrdersIndexRoute = AdminProductOrdersIndexImport.update({
  id: '/admin/productOrders/',
  path: '/admin/productOrders/',
  getParentRoute: () => rootRoute,
} as any)

const AdminOrdersIndexRoute = AdminOrdersIndexImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRoute,
} as any)

const AdminOffersIndexRoute = AdminOffersIndexImport.update({
  id: '/admin/offers/',
  path: '/admin/offers/',
  getParentRoute: () => rootRoute,
} as any)

const AdminCarsIndexRoute = AdminCarsIndexImport.update({
  id: '/admin/cars/',
  path: '/admin/cars/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/aboutus': {
      id: '/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/': {
      id: '/admin/cars/'
      path: '/admin/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminCarsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/offers/': {
      id: '/admin/offers/'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/productOrders/': {
      id: '/admin/productOrders/'
      path: '/admin/productOrders'
      fullPath: '/admin/productOrders'
      preLoaderRoute: typeof AdminProductOrdersIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/contact': typeof ContactRoute
  '/offer': typeof OfferRoute
  '/services': typeof ServicesRoute
  '/thank-you': typeof ThankYouRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/offers': typeof OffersIndexRoute
  '/admin/cars': typeof AdminCarsIndexRoute
  '/admin/offers': typeof AdminOffersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/productOrders': typeof AdminProductOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/contact': typeof ContactRoute
  '/offer': typeof OfferRoute
  '/services': typeof ServicesRoute
  '/thank-you': typeof ThankYouRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/offers': typeof OffersIndexRoute
  '/admin/cars': typeof AdminCarsIndexRoute
  '/admin/offers': typeof AdminOffersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/productOrders': typeof AdminProductOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/contact': typeof ContactRoute
  '/offer': typeof OfferRoute
  '/services': typeof ServicesRoute
  '/thank-you': typeof ThankYouRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/productOrders/': typeof AdminProductOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/contact'
    | '/offer'
    | '/services'
    | '/thank-you'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/register'
    | '/admin'
    | '/offers'
    | '/admin/cars'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/productOrders'
    | '/admin/products'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/contact'
    | '/offer'
    | '/services'
    | '/thank-you'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/register'
    | '/admin'
    | '/offers'
    | '/admin/cars'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/productOrders'
    | '/admin/products'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/aboutus'
    | '/contact'
    | '/offer'
    | '/services'
    | '/thank-you'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/register'
    | '/admin/'
    | '/offers/'
    | '/admin/cars/'
    | '/admin/offers/'
    | '/admin/orders/'
    | '/admin/productOrders/'
    | '/admin/products/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutusRoute: typeof AboutusRoute
  ContactRoute: typeof ContactRoute
  OfferRoute: typeof OfferRoute
  ServicesRoute: typeof ServicesRoute
  ThankYouRoute: typeof ThankYouRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  AdminCarsIndexRoute: typeof AdminCarsIndexRoute
  AdminOffersIndexRoute: typeof AdminOffersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductOrdersIndexRoute: typeof AdminProductOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutusRoute: AboutusRoute,
  ContactRoute: ContactRoute,
  OfferRoute: OfferRoute,
  ServicesRoute: ServicesRoute,
  ThankYouRoute: ThankYouRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  AdminCarsIndexRoute: AdminCarsIndexRoute,
  AdminOffersIndexRoute: AdminOffersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductOrdersIndexRoute: AdminProductOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aboutus",
        "/contact",
        "/offer",
        "/services",
        "/thank-you",
        "/auth/login",
        "/auth/profile",
        "/auth/register",
        "/admin/",
        "/offers/",
        "/admin/cars/",
        "/admin/offers/",
        "/admin/orders/",
        "/admin/productOrders/",
        "/admin/products/",
        "/admin/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/aboutus": {
      "filePath": "aboutus.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/offer": {
      "filePath": "offer.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/thank-you": {
      "filePath": "thank-you.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/profile": {
      "filePath": "auth/profile.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/offers/": {
      "filePath": "offers/index.tsx"
    },
    "/admin/cars/": {
      "filePath": "admin/cars/index.tsx"
    },
    "/admin/offers/": {
      "filePath": "admin/offers/index.tsx"
    },
    "/admin/orders/": {
      "filePath": "admin/orders/index.tsx"
    },
    "/admin/productOrders/": {
      "filePath": "admin/productOrders/index.tsx"
    },
    "/admin/products/": {
      "filePath": "admin/products/index.tsx"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
